apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mysecret-sops
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:9yDqL+VImd3d4GI4WuQ=,iv:hRLZgqkVKwIuwY5KNrOgbSkyjF5JvoHnWibkPrggFfc=,tag:oysui9qKG0tCIb9hxWymPg==,type:str]
      labels:
        label1: ENC[AES256_GCM,data:8mIYHk9EHOKc1s/G8g==,iv:5NYHRTVcX/bOfAUq27opMnZJRgodt82tqmf/MGeAjPA=,tag:DWRL1SmDIwfevIoQ/H/pLw==,type:str]
      annotations:
        key1: ENC[AES256_GCM,data:JsnRFMGDfVaS0w==,iv:jW4pXlPdBm+82YkTWRJe+sqllmvpzonhKB5LcdENACY=,tag:38BLvuxsfzgWht5TbCNOPw==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:OuBtalyYiQfiY1yjO/IMvuMtDw==,iv:ffmlI3P2gXG9nVQmI1v6K9OQiSckjxD/wb8b0fGI1Sc=,tag:0CeUQc3hrurgyMAqOyVIbQ==,type:str]
    - name: ENC[AES256_GCM,data:afpm292HAK7zQ0nmnw==,iv:WNKkTvHpcQo/PJP7JwJbUz5+4JJxkxX5xhYSSzzVQLI=,tag:pJhBfECKRycYqwzVXuljeQ==,type:str]
      data:
        data-name1: ENC[AES256_GCM,data:P0pa/tkl0GuSioRKe2fpKw==,iv:nItlNiI3oAFw5WjJWfn0zj1v3eDb2310eC5JcIhHwjk=,tag:ohCc86OgO1Dijsn/w6RsKA==,type:str]
    - name: ENC[AES256_GCM,data:Food4YLzsoJvHIZrhg==,iv:kXvc2SM1FVDX7eEtyDnSFTOYr9mhRNk7bE90+T37fx8=,tag:CmAG0TNW8RqkqFBTBrOUvA==,type:str]
      stringData:
        token: ENC[AES256_GCM,data:yXc0EN07ZelNDe7gH2FGLw==,iv:E7Zx7WJjghma4nIPnrxhC/jTEUws0IGwjduB27VQ0kw=,tag:cSr9TctaxYb/5cKRktFSnA==,type:str]
    - name: ENC[AES256_GCM,data:gD3yyAnr8bhLpOD0,iv:mvr9gDFvsOZ2I0LjUVkHxqIldjeEinb2hhLOMrCk2p0=,tag:Z+dB8euj72UpRyRCLtduxw==,type:str]
      type: ENC[AES256_GCM,data:3mDLdhhJKq55KTZL/t7lVt4aj/EjtCVfBHI64AzE,iv:E6Lvwyx8NmYayjJ1bvDBsMwQsfmsNsg/8jTaN2Kufus=,tag:BMZdWe6OGUV0Qwj+i6Y0yw==,type:str]
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:B88fcQhPF6ftVJskN0rfoHCIg8Bk9z16La5qOpMS3cQW7SJpD7br1XGx4kzIF3139oClZL2fHmq4nPgpJCQ6FbrFzBeNtqpn20FbR4XYa/14Wssuey2qUCpY0sb1jEZ1Gi03zTHKRWiUfmBIuGqfcsLzwy0=,iv:NTKY26Y1bvOSj3QeEOj+TJ72lyPDjL+BCOXkTJgRsK4=,tag:Zorbtb4iymZgGGKdXinXdA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ1NOcExmM0QrUGVUTHVL
        NmEwNzR4UGlBTXUvVWFIOGh2ZTE4QXVHdUIwCnVPWUZIU0ZOTUhIR1lFSjVEVlhS
        QXFkbWROa2hIcGdVNkpYd3BkMktoZHMKLS0tIEZIZG1ITHFpdm1aZ3RxcmFkdERL
        TEJZY3RaT09NMzc4eGdRODEwVC9iQWMK2tC5t4kdtxcRYgCRn3j4E6jSyQIvzdZz
        XIw0B0whTkg35+e5YuLIeOZP0MJzTd9sycG8S4aLz1xQGnRp1Au6Hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-21T14:51:35Z"
  mac: ENC[AES256_GCM,data:JtwIlxraUHAcxEHZVoe18CnaszI+xj/VaPLaZFgfiBkK2NJIPvS+lKG5jxAoMRZzjXxhJZGUf63wPeSC5cZ416iD9xBHxTMNNQRkVYzFQTlUM7qex+fpr0AiiPL/zPfSEg2x/LJ0YDCxO+c1Ug6TtMWGfVFri84NBOFnfE+yd3A=,iv:NdY2rBfEDWyv+a50qwH88D8kfGzZWngzrbsOmsHtC1o=,tag:8Y+MnF18d37dkP9ApvvT+Q==,type:str]
  pgp: []
  encrypted_suffix: Templates
  version: 3.9.1

  
